#配置数据源文件
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-jpa-0909?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
